# Default values for laa-maat-scheduled-tasks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-crime-apps-team/laa-maat-scheduled-tasks-dev
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "maat-scheduled-tasks"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8499

# TODO ingress config
ingress:
  enabled: true
  environmentName: laa-maat-scheduled-tasks-uat
  className: default
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
  hosts:
    - host: laa-maat-scheduled-tasks-uat.apps.live.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: "Prefix"
  tls: []


# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

aws_region: eu-west-2

host_env: uat
sentry:
  sampleRate: 0.05
    
logging:
  level: INFO

actuator:
  metrics:
    enabled: true
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  port: 8510
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

jwt:
  issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_uKC0C8X8e

cclfApi:
  baseUrl: https://cclf-uat.apps.live.cloud-platform.service.justice.gov.uk/cclf/api/v1
  oauthUrl: https://cclf-uat.auth.eu-west-2.amazoncognito.com/oauth2/token

ccrApi:
  baseUrl: https://ccr-uat.apps.live.cloud-platform.service.justice.gov.uk/ccr/api/v1
  oauthUrl: https://ccr-uat.auth.eu-west-2.amazoncognito.com/oauth2/token
