server:
  port: 8499

management:
  server:
    port: 8510
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: maat-scheduled-tasks
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      max-lifetime: 1900000          # 31 mins+
      leak-detection-threshold: 1860000  # ~31 mins
      idle-timeout: 600000           # 10 mins
    prometheus:
      enabled: true

maat_batch:
  lmr_reports:
    cron_expression:  ${LMR_REPORTS}
  evidence_reminder_letter:
    cron_expression:  ${EVIDENCE_REMINDER_LETTER}
  inactive_users:
    cron_expression: ${INACTIVATE_USERS}
  fa_fix:
    cron_expression: ${FA_FIX}
  central_print:
    cron_expression: ${CENTRAL_PRINT}

xhibit-batch:
  appeal_data_processing:
    cron_expression: ${APPEAL_DATA_CRON_EXPRESSION}
  trial_data_processing:
    cron_expression: ${TRIAL_DATA_CRON_EXPRESSION}

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: ${SENTRY_SAMPLE_RATE}

services:
  cclf-api:
    base-url: ${CCLF_API_BASE_URL}
    registrationId: cclf

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadGateway
          - org.springframework.web.reactive.function.client.WebClientResponseException.TooManyRequests
          - org.springframework.web.reactive.function.client.WebClientResponseException.ServiceUnavailable
          - org.springframework.web.reactive.function.client.WebClientResponseException.GatewayTimeout
