apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-maat-scheduled-tasks.fullname" . }}
  labels:
    {{- include "laa-maat-scheduled-tasks.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laa-maat-scheduled-tasks.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laa-maat-scheduled-tasks.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laa-maat-scheduled-tasks.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if not (eq (toString .Values.actuator.port) "http") }}
            - name: actuator
              containerPort: {{ .Values.actuator.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.actuator }}
          livenessProbe:
            httpGet:
              path: {{ .health.path }}
            {{- if not (eq (toString .port) "http") }}
              port: actuator
            {{- else }}
              port: http
            {{- end }}
            initialDelaySeconds: {{ .liveness.initialDelaySeconds }}
            periodSeconds: {{ .liveness.periodSeconds }}
            timeoutSeconds: {{ .liveness.timeoutSeconds }}
            failureThreshold: {{ .liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .health.path }}
            {{- if not (eq (toString .port) "http") }}
              port: actuator
            {{- else }}
              port: http
            {{- end }}
            initialDelaySeconds: {{ .readiness.initialDelaySeconds }}
            periodSeconds: {{ .readiness.periodSeconds }}
            timeoutSeconds: {{ .readiness.timeoutSeconds }}
            failureThreshold: {{ .readiness.failureThreshold }}
          {{- end }}
          {{ include "laa-maat-scheduled-tasks.env-vars" . | nindent 10 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}