{{- if .Values.actuator.metrics.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "laa-maat-scheduled-tasks.fullname" . }}-monitoring
  labels:
    {{- include "laa-maat-scheduled-tasks.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "laa-maat-scheduled-tasks.fullname" .}}
      {{- include "laa-maat-scheduled-tasks.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            component: monitoring
{{- end }}