name: Slack channel notification
description: "Send notification to Slack channel"

inputs:
  slack-channel:
    description: "The name of the Slack channel to which notifications will be sent. Default - laa-crimeapps-ci"
    required: false
    default: "laa-crimeapps-ci"
  webhook-url:
    description: "The webhook URL of the Slack channel."
    required: true

runs:
  using: "composite"
  steps:
    - name: Notify success to Slack
      id: slack-success
      if: ${{ success() }}
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:white_check_mark: Succeeded GitHub Actions*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repo*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit*\n<${{ github.event.head_commit.url }}|${{ env.SHORT_SHA }}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Author*\n${{ github.event.head_commit.author.name }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Job*\n`${{ github.job }}`"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event Name*\n`${{ github.event_name }}`"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow*\n`${{ github.workflow }}`"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Build Logs*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Took*\n`${{ steps.calculate_duration.outputs.duration }} sec`"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Message*\n${{ github.event.head_commit.message }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Notify failure to Slack (non-main branches only)
      if: ${{ failure() && github.ref_name != 'main' }}
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,ref,workflow,job,took
        text: |
          :x: Deployment failed in *${{ github.workflow }}*  
          *Repo:* ${{ github.repository }}  
          *Branch:* ${{ github.ref_name }}  
          *Job:* ${{ github.job }}  
          *Actor:* ${{ github.actor }}  
          *Run:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK